// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi0hOPrpcQOpnx8zujmbptx8ntq7X8uj4',
    appId: '1:1089576024888:web:98c02efdc113e426c69fcd',
    messagingSenderId: '1089576024888',
    projectId: 'phoneauthproject-77ae7',
    authDomain: 'phoneauthproject-77ae7.firebaseapp.com',
    storageBucket: 'phoneauthproject-77ae7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5M6pukZtLilY-5uQykSPLH7oDWyqp7RQ',
    appId: '1:1089576024888:android:c8a123985f66f320c69fcd',
    messagingSenderId: '1089576024888',
    projectId: 'phoneauthproject-77ae7',
    storageBucket: 'phoneauthproject-77ae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrCAYMpplxqDQwyZNzNp92NL9peo9BSiM',
    appId: '1:1089576024888:ios:375e4ba1bea356b5c69fcd',
    messagingSenderId: '1089576024888',
    projectId: 'phoneauthproject-77ae7',
    storageBucket: 'phoneauthproject-77ae7.appspot.com',
    androidClientId: '1089576024888-degba4fukj2pnpbhnrke682fr3870d0m.apps.googleusercontent.com',
    iosClientId: '1089576024888-ttlqb8q48tsjesklp6jgvnpmg9i931es.apps.googleusercontent.com',
    iosBundleId: 'com.example.userapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrCAYMpplxqDQwyZNzNp92NL9peo9BSiM',
    appId: '1:1089576024888:ios:375e4ba1bea356b5c69fcd',
    messagingSenderId: '1089576024888',
    projectId: 'phoneauthproject-77ae7',
    storageBucket: 'phoneauthproject-77ae7.appspot.com',
    androidClientId: '1089576024888-degba4fukj2pnpbhnrke682fr3870d0m.apps.googleusercontent.com',
    iosClientId: '1089576024888-ttlqb8q48tsjesklp6jgvnpmg9i931es.apps.googleusercontent.com',
    iosBundleId: 'com.example.userapp',
  );
}
